apiVersion: v1
kind: Service
metadata:
  name: drycc-victoriametrics-vmselect
  labels:
    app: drycc-victoriametrics-vmselect
    heritage: drycc
spec:
  ports:
  - port: 8481
    name: http
    targetPort: 8481
  selector:
    app: drycc-victoriametrics-vmselect
