apiVersion: v1
kind: Service
metadata:
  name: drycc-victoriametrics-vmselect
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8481"
    prometheus.io/path: "/metrics"
  labels:
    app: drycc-victoriametrics
    heritage: drycc
    component: drycc-victoriametrics-vmselect
spec:
  clusterIP: None
  ports:
  - port: 8481
    name: http
    targetPort: 8481
  selector:
    app: drycc-victoriametrics
    component: drycc-victoriametrics-vmselect
