apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: drycc-victoriametrics
spec:
  podSelector:
    matchLabels:
      app: drycc-victoriametrics
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{.Release.Namespace}}
      podSelector:
        matchLabels:
          app: drycc-controller-api
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{.Release.Namespace}}
      podSelector:
        matchLabels:
          app: drycc-victoriametrics
