apiVersion: v1
kind: Service
metadata:
  name: drycc-victoriametrics-vminsert
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8480"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: drycc-victoriametrics-vminsert
  ports:
  - name: http
    port: 8480
    targetPort: 8480
