{{- $replicas := .Values.vmstorage.replicas | int -}}
{{- $endpoints := list -}}
{{- range $i := until $replicas -}}
  {{- $endpoint := printf "drycc-victoriametrics-vmstorage-%d.drycc-victoriametrics-vmstorage.%s.svc.%s:8400" $i $.Release.Namespace $.Values.global.clusterDomain -}}
  {{- $endpoints = append $endpoints $endpoint -}}
{{- end -}}
{{- $storageNodes := join "," $endpoints -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-victoriametrics-vminsert
  labels:
    app: drycc-victoriametrics
    heritage: drycc
    component: drycc-victoriametrics-vminsert
spec:
  replicas: {{ .Values.vminsert.replicas }}
  selector:
    matchLabels:
      app: drycc-victoriametrics
      component: drycc-victoriametrics-vminsert
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: drycc-victoriametrics
        component: drycc-victoriametrics-vminsert
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.vminsert.podAffinityPreset.type "component" "" "extraMatchLabels" .Values.vminsert.podAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.vminsert.podAntiAffinityPreset.type "component" "" "extraMatchLabels" .Values.vminsert.podAntiAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.vminsert.nodeAffinityPreset.type "key" .Values.vminsert.nodeAffinityPreset.key "values" .Values.vminsert.nodeAffinityPreset.values ) | nindent 10 }}
      initContainers:
      - name: drycc-victoriametrics-vminsert-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - netcat
        - -v
        - -a
        - {{ $storageNodes }}
      containers:
      - name: drycc-victoriametrics-vminsert
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/victoriametrics:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- else }}
        args:
        - vminsert
        - --httpListenAddr=:8480
        - --storageNode={{ $storageNodes }}
        {{- if .Values.vminsert.extraArgs }}
        {{- include "common.tplvalues.render" (dict "value" .Values.vminsert.extraArgs "context" $) | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- with index .Values "vminsert" "resources" }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 8480
        livenessProbe:
          tcpSocket:
            port: 8480
        readinessProbe:
          httpGet:
            path: /health
            port: 8480
        startupProbe:
          httpGet:
            path: /health
            port: 8480
