apiVersion: v1
kind: Secret
metadata:
  name: victoriametrics-vmauth-creds
  labels:
    heritage: drycc
type: Opaque
data:
  username: {{ .Values.vmauth.username | b64enc }}
  password: {{ .Values.vmauth.password | b64enc }}
