apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-vmauth-config
  labels:
    heritage: drycc
data:
  vmauth.yaml: |
    users:
    - username: {{ .Values.vmauth.username }}
      password: {{ .Values.vmauth.password }}
      url_map:
      - src_paths:
        - "/insert"
        url_prefix: "http://drycc-victoriametrics-vminsert.{{.Release.Namespace}}.svc.{{.Values.global.clusterDomain}}:8480/"
      url_prefix: "http://drycc-victoriametrics-vmselect.{{.Release.Namespace}}.svc.{{.Values.global.clusterDomain}}:8481/"
      discover_backend_ips: true
