{{ $username := include "common.secrets.lookup" (dict "secret" "victoriametrics-vmauth-creds" "key" "username" "defaultValue" (default (randAlphaNum 16) .Values.vmauth.username) "context" $) }}
{{ $password := include "common.secrets.lookup" (dict "secret" "victoriametrics-vmauth-creds" "key" "password" "defaultValue" (default (randAlphaNum 32) .Values.vmauth.password) "context" $) }}
apiVersion: v1
kind: Secret
metadata:
  name: victoriametrics-vmauth-creds
  labels:
    heritage: drycc
type: Opaque
data:
  username: {{ $username }}
  password: {{ $password }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-vmauth-config
  labels:
    heritage: drycc
data:
  vmauth.yaml: |
    users:
    - username: {{ $username | b64dec }}
      password: {{ $password | b64dec }}
      url_map:
      - src_paths:
        - "/insert"
        url_prefix: "http://drycc-victoriametrics-vminsert.{{.Release.Namespace}}.svc.{{.Values.global.clusterDomain}}:8480/"
      url_prefix: "http://drycc-victoriametrics-vmselect.{{.Release.Namespace}}.svc.{{.Values.global.clusterDomain}}:8481/"
      discover_backend_ips: true
