apiVersion: v1
kind: Service
metadata:
  name: drycc-victoriametrics-vmauth
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8427"
    prometheus.io/path: "/metrics"
  labels:
    app: drycc-victoriametrics
    heritage: drycc
    component: drycc-victoriametrics-vmauth
spec:
  clusterIP: None
  ports:
  - port: 8427
    name: http
    targetPort: 8427
  selector:
    app: drycc-victoriametrics
    component: drycc-victoriametrics-vmauth
